<template>
  <slot name="nav"></slot>
  <slot name="content">
      <div class="about hidden-scrollbar" id="content" @scroll="$emit('scrollHandle')">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nunc diam, facilisis nec blandit quis, scelerisque ut erat. Praesent quam libero, aliquam non metus et, hendrerit sodales justo. Maecenas vel mattis ex, at pellentesque erat. Etiam maximus velit sem, eu viverra massa hendrerit quis. In lobortis faucibus pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et rhoncus ipsum. Curabitur eget pellentesque urna, at suscipit risus. Pellentesque luctus rutrum scelerisque. Mauris tristique gravida dolor, sed faucibus nunc luctus ac. Maecenas aliquam lacus odio, a molestie mi scelerisque vel. Proin tristique leo eget diam dapibus, et egestas erat dapibus. Suspendisse in scelerisque ligula. Sed fermentum tincidunt ipsum. In in leo id leo tempus laoreet.

          Nulla tincidunt mattis tellus. Donec ut neque lacinia, rhoncus lectus in, mollis tortor. Sed turpis nisl, sagittis id fermentum eu, eleifend vitae nisl. Vestibulum egestas mattis elementum. Integer volutpat velit nibh, eu porta lorem commodo vitae. Vivamus rutrum sagittis nisl. In porta tincidunt sem non euismod. Duis volutpat posuere neque, in suscipit enim pulvinar in. Vivamus leo orci, lobortis vehicula odio quis, suscipit auctor justo. Suspendisse potenti. Vivamus eget metus eget dui varius posuere pharetra nec diam. Curabitur tincidunt varius urna at feugiat. Praesent fermentum leo sit amet metus pellentesque, nec egestas massa pharetra. In et orci purus. Vivamus id nisi consequat urna posuere ullamcorper et non magna. Etiam feugiat varius varius.

          Donec sed nulla dolor. Vivamus hendrerit, nulla sed placerat feugiat, erat risus tristique sapien, ac venenatis erat ipsum a erat. Morbi volutpat ullamcorper augue eget posuere. Proin nec luctus orci, ac pellentesque leo. Fusce tincidunt dapibus quam vitae efficitur. Suspendisse eget accumsan urna, vel posuere metus. Integer vel mollis dolor, et euismod ipsum. Praesent eu ullamcorper odio. Ut at dui arcu. Sed in eros id urna semper efficitur. Pellentesque posuere risus mi. Cras pulvinar sagittis dictum. Integer a nunc nec ipsum vulputate facilisis et nec lacus. Ut ultrices porttitor dapibus. Proin consequat ex at purus interdum feugiat.

          Aliquam faucibus pulvinar magna quis commodo. Sed vel lacinia quam. Morbi faucibus congue sapien id imperdiet. Suspendisse sapien turpis, ultrices non imperdiet vel, rutrum ut lacus. Phasellus sit amet dapibus velit, et pretium eros. Suspendisse purus felis, sodales eu auctor non, luctus faucibus justo. Vestibulum tempor sit amet elit ac tincidunt. Etiam libero lorem, gravida nec velit non, maximus ornare mauris. Pellentesque scelerisque mi et magna interdum tempus. Nulla condimentum nulla in urna vestibulum lacinia. Praesent sit amet sagittis nibh, in tincidunt arcu.

          Integer porta consequat turpis, nec ultrices ex sodales ac. Nam non eros elementum, vehicula tellus eget, pulvinar eros. Nullam metus nisl, lobortis sed diam nec, mollis tempus leo. Donec tempus volutpat nisi. Nullam non felis eu eros eleifend pretium at id tortor. Donec vitae eros felis. In sapien felis, dictum id lacinia id, sollicitudin eget mi. Donec dapibus sed nibh sit amet sollicitudin. Vivamus a turpis purus. Suspendisse sollicitudin tristique dolor ac semper. Aliquam at molestie justo. Aliquam ullamcorper elit tortor, nec varius lacus volutpat a. Sed commodo tellus lacus, luctus ullamcorper metus elementum quis. Aenean semper semper tellus.

          Nam eget eros odio. Fusce in ex augue. Proin placerat eros sed consequat semper. Curabitur orci erat, fermentum vitae rhoncus nec, laoreet sed nunc. Pellentesque non semper sapien, non laoreet turpis. Morbi non pretium mi. Mauris blandit ipsum dictum ex faucibus convallis. Vestibulum vel diam ex. Aliquam luctus pellentesque suscipit.

          Morbi rhoncus nisi vel commodo aliquet. Ut pulvinar metus non mattis posuere. Etiam ante eros, iaculis id vehicula eget, hendrerit quis lorem. Phasellus ullamcorper odio ut magna dignissim cursus. Etiam sed faucibus nibh. Quisque in urna pretium, iaculis felis id, pharetra lectus. Phasellus eleifend purus arcu. Quisque facilisis malesuada neque fermentum euismod. Cras ultrices sit amet ligula sed vestibulum. Cras varius quam eget elit posuere aliquet. Nunc sit amet nisi nec tortor ullamcorper sollicitudin eget et mauris. Nam dapibus, elit in vehicula vestibulum, nibh est accumsan nibh, ac volutpat arcu sapien nec tellus. Integer vulputate, dolor et iaculis viverra, felis magna porta sem, id tincidunt velit tellus sed felis.

          Sed sapien massa, venenatis nec ullamcorper et, pretium ut lacus. Donec eu efficitur massa. Duis quis augue auctor, aliquet arcu at, porta mi. Duis ut lacus vitae nulla faucibus rhoncus. Phasellus placerat interdum odio, in faucibus sem aliquet semper. Suspendisse suscipit nisl et nunc rutrum, facilisis facilisis orci dignissim. Nulla eget purus quam.

          Cras vitae sagittis augue, sit amet iaculis leo. Morbi neque nulla, congue ac mi vel, volutpat ultricies sapien. Etiam in ornare ligula. Suspendisse imperdiet est sed ligula porta, nec imperdiet urna scelerisque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus quis volutpat elit, et tristique metus. Morbi non velit maximus, porta mi sit amet, vulputate ligula. Duis scelerisque placerat congue. Fusce eu blandit lectus. Pellentesque volutpat et metus quis pharetra. Nam tempus pharetra risus ultricies mollis. Suspendisse tincidunt ut purus non eleifend. Aenean mollis efficitur neque ut dapibus. Ut consequat tincidunt mi, vitae fringilla est facilisis vitae.

          Etiam at nulla ut leo pulvinar laoreet. Integer eget lorem nec nulla posuere vehicula. Sed enim leo, bibendum in blandit eget, viverra sed nisl. Fusce finibus ac risus vitae aliquet. Quisque et venenatis metus, in vulputate velit. In vulputate congue porttitor. Sed mollis, sem sit amet tristique venenatis, est elit vulputate urna, sit amet ultrices mi ligula quis massa. Etiam sed est non augue interdum efficitur. Donec ut dolor non lorem dictum tincidunt. In sed ligula tempor quam pretium rhoncus non et ligula. Sed velit velit, sagittis in pharetra eget, vehicula in libero. Nullam vitae bibendum lorem.

          Donec ornare malesuada massa, vel iaculis justo lacinia nec. Praesent aliquet felis ut leo accumsan, quis suscipit urna interdum. Nam eu venenatis orci. Curabitur at eros sem. Curabitur ultrices, tellus ac posuere ultricies, neque eros eleifend nunc, quis auctor sapien sapien sit amet tortor. Ut pretium libero nec suscipit porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis turpis ut leo vulputate lacinia sit amet ac nulla. Quisque congue faucibus facilisis. Nulla nec lorem ut elit rutrum malesuada nec ut turpis. Quisque sit amet ullamcorper purus. Vestibulum rhoncus risus massa, at volutpat magna consequat sed. Curabitur ullamcorper leo lorem, quis aliquet arcu placerat vitae.

          Vestibulum vel facilisis tellus. Morbi a dolor nisi. Nunc id elit ut lectus semper pharetra. Curabitur id erat accumsan, cursus augue non, vehicula lorem. Duis libero justo, rhoncus gravida rhoncus non, hendrerit eget tortor. Pellentesque porttitor, odio vel interdum faucibus, velit magna imperdiet lectus, ut tincidunt ipsum diam non justo. Aliquam fermentum nisi ac purus pharetra suscipit. Etiam vitae ligula et purus convallis vehicula. Proin dictum metus sit amet tincidunt pharetra. Vestibulum imperdiet dignissim ultrices. Sed sagittis leo enim, malesuada pretium mauris viverra nec. Cras in suscipit massa. Nullam fringilla libero vitae varius imperdiet. Vivamus rutrum faucibus commodo. Aliquam consectetur metus quis magna pharetra ultricies.

          Integer tempus, sapien a condimentum fringilla, urna arcu accumsan augue, quis maximus augue lacus eget nibh. Ut et consectetur dolor. Donec efficitur efficitur purus sed iaculis. Proin egestas scelerisque quam, a sodales urna dignissim maximus. Sed eget urna rutrum, ultrices nunc vel, porta eros. Duis iaculis rutrum lacus. Morbi facilisis molestie libero, eget laoreet tortor mattis sed. Sed sit amet ornare diam, sed faucibus sapien.

          Ut dictum tempor est at aliquet. Sed vitae erat sed dolor elementum vestibulum rutrum eu orci. Aliquam molestie nunc et dui aliquam feugiat. Nulla viverra magna et cursus ultrices. Nam turpis risus, hendrerit gravida libero in, vehicula vulputate turpis. Vestibulum eu neque vel sapien posuere accumsan. Morbi quis sapien et sapien fringilla malesuada et eget diam. Integer tempus magna malesuada, pharetra urna eleifend, fermentum tellus. Ut molestie convallis ex, eu scelerisque turpis. Nunc quam ex, finibus id lobortis eleifend, congue in tellus.

          Morbi tortor dui, maximus ut egestas nec, molestie non tellus. Pellentesque auctor dui sit amet tellus pretium, et aliquam diam hendrerit. Integer aliquam consectetur ante ut consequat. Cras congue purus nibh, nec congue neque efficitur in. Aenean condimentum justo ut congue malesuada. Praesent efficitur massa nec ante dapibus tempus. Sed venenatis est eget viverra hendrerit.

          Nullam vestibulum hendrerit dui at condimentum. Proin porta imperdiet lobortis. Pellentesque ac luctus augue, ac condimentum diam. Sed in nibh nec lectus scelerisque vehicula ut at elit. Vivamus aliquet nibh ac libero pellentesque, ut ultricies nibh porta. Integer at volutpat nulla. Duis nisl diam, porttitor sit amet egestas vitae, mattis mollis diam. Suspendisse rhoncus, nulla eu maximus condimentum, orci elit lacinia dui, nec suscipit risus tortor nec mi. Quisque nulla felis, mollis quis mattis aliquet, pulvinar a tortor. Etiam pharetra, sem non ultrices placerat, mi leo commodo neque, eu maximus nulla velit sit amet felis. Donec non erat commodo enim sodales faucibus. Praesent sollicitudin tortor vel ipsum pharetra sagittis. Morbi a faucibus purus. Pellentesque volutpat, sem sed iaculis aliquet, quam velit rutrum purus, et dictum purus magna eu justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque nec nibh metus.

          Aenean sed varius mi, id auctor est. Duis ac vulputate quam, eget pulvinar ipsum. Pellentesque eu bibendum enim. Quisque pellentesque eu ante eu vestibulum. Etiam quis scelerisque urna. Nam leo augue, placerat at vehicula a, mollis et enim. Fusce placerat ante at lorem congue, non posuere elit pharetra. In efficitur mattis enim sed placerat. Aenean imperdiet orci a nibh faucibus, consequat pulvinar leo tincidunt. Phasellus semper libero lorem, vel consectetur nisi tristique in.

          Cras et mi interdum, sagittis ex sed, lobortis neque. Ut venenatis, ante id convallis ornare, lacus est bibendum dolor, quis auctor augue libero sit amet est. Nunc tristique, tellus at interdum viverra, tortor dolor blandit lorem, quis maximus nunc ante finibus lorem. Praesent a leo sapien. Aenean sodales velit nec velit scelerisque, convallis finibus mauris tincidunt. Ut sit amet lectus libero. Nulla facilisi. Integer nec viverra neque. Ut tortor odio, tempus non lacinia a, mattis sit amet massa.

          Phasellus vestibulum tellus a venenatis efficitur. Vestibulum aliquet sem sed ornare iaculis. Aenean et vulputate risus. Curabitur eu interdum lorem. Donec non egestas mauris, ac dapibus ligula. Phasellus bibendum efficitur est, in semper risus. Nullam aliquet elit at ultricies elementum. Etiam non erat mauris. Donec sem neque, varius pulvinar odio maximus, efficitur semper velit. Donec laoreet eros a tortor finibus fermentum. Aliquam sit amet ipsum eget felis semper cursus nec sed sapien. Donec lobortis a augue ac hendrerit. Fusce varius volutpat ipsum et interdum. Fusce vel quam eu mauris porttitor gravida at in orci.

          Pellentesque nec nunc vel nulla tempor feugiat. Sed a nibh velit. Duis condimentum magna quis dolor sagittis, fermentum condimentum est blandit. Donec placerat vel metus eget lobortis. Praesent at turpis sem. Nam sed turpis viverra, lobortis leo ac, mattis nisl. Quisque bibendum turpis id viverra bibendum. Ut mollis efficitur arcu, lobortis auctor urna rutrum et. Pellentesque convallis mauris elit, sed semper magna congue ut. Nam consectetur sodales tellus id molestie. Etiam commodo elit ac ipsum convallis, sit amet scelerisque nulla feugiat. Ut porta, purus in imperdiet consequat, augue felis dapibus augue, et lobortis ex felis nec lectus. Nullam erat dui, venenatis sit amet turpis vitae, pharetra venenatis mi. Phasellus venenatis finibus arcu, sed varius arcu suscipit ac. Suspendisse quam nulla, convallis sed diam ac, imperdiet eleifend orci.
      </div>
  </slot>
  <slot name="background">
      <div class="background" v-bind="$attrs">
          <div class="background_wrapper">
              <img class="background_image_fond" src="~@/assets/fond_montagne_vert/sky_fc.png"/>
              <img class="background_image" src="~@/assets/fond_montagne_vert/far_mountains_fc.png"/>
              <img class="background_image" src="~@/assets/fond_montagne_vert/grassy_mountains_fc.png"/>
              <img class="background_image" src="~@/assets/fond_montagne_vert/clouds_mid_t_fc.png"/>
              <img class="background_image" src="~@/assets/fond_montagne_vert/clouds_mid_fc.png"/>
              <img class="background_image" src="~@/assets/fond_montagne_vert/hill.png"/>
              <img class="background_image" src="~@/assets/fond_montagne_vert/clouds_front_t_fc.png"/>
              <img class="background_image" src="~@/assets/fond_montagne_vert/clouds_front_fc.png"/>
          </div>
      </div></slot>
</template>

<script>

  export default {
    name: 'AboutView',
  }
</script>
